### ISSUE TITLE
Windows Store Support?

### ISSUE THREAD

**Issue by BittahBandit1** [Lyall/SoulHackers2Fix#1]
Does this work with the Windows Store version of the game? If not, will it work in the future?

**Comment by Lyall** [comment]
Honestly, I don't know for sure as I haven't tested it but it probably will work okay. I've used BepInEx on several Microsoft Store games. As long as the game supports the advanced install features in the Xbox app then you can access the games folder. The only difference with the Microsoft Store version is that you would be extracting the fix in to <GameDir>\Content\ as the main directory.  

If you have the Microsoft Store version, give it a try and let me know. It would be good to know for sure that it works!

**Comment by BittahBandit1** [comment]
Hey there, I can't seem to get it to work. I set the config file to 2560x1600 (res of my monitor) but it's still 1440p letterboxed and I can't change it in game. Even if I choose 640x480 in game it's still at 1440p

**Comment by Lyall** [comment]
Can you upload your log file? You can find it in `BepInEx\LogOutput.log`.

**Comment by BittahBandit1** [comment]
Nevermind, was able to fix it by restarting my computer lol

**Comment by Lyall** [comment]
Glad to hear it's all working!
