### ISSUE TITLE
How to force the game to run on primary monitor

### ISSUE THREAD

**Issue by vjperez724** [Lyall/SoulHackers2Fix#2]
The game opens on a secondary monitor and with this patch I don't seem to have a way to move it.  Any ideas?

**Comment by Lyall** [comment]
I've updated how the custom resolution patch works in [v0.0.2](https://github.com/Lyall/SoulHackers2Fix/releases). You should still be able to use the in-game option of "target display" to choose which monitor to display the game on. Let me know if it's still not working with this newer version.

**Comment by vjperez724** [comment]
Works great, thanks.  The targeted displays are a little weird (primary is #3), but that's not really an issue. 

Also, just in case anyone runs into this problem in the future, simple workaround for it is just to deactivate the monitors you don't want, then enable after the game is running.
